spring: 
  profiles: 
    active: 
    - dev
---
spring: 
  profiles: dev     #开发环境
  application: 
    name: mircroservicecloud-config-xk-dev
---
spring: 
  profiles: test     #测试环境
  application: 
    name: mircroservicecloud-config-xk-test
