spring: 
  profiles: 
    active: 
    - dev
---
server:
  port: 7001 #注册中心占用7001端口，冒号后必须有空格
spring: 
  profiles: dev     #开发环境
  application: 
    name: mircroservicecloud-config-eureka-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #自身不注册进eureka
    fetch-registry: false #不通过eureka获取注册信息
    service-url: 
      defaultZone: http://eureka7001.com:7001/eureka/
---
server:
  port: 7001
spring: 
  profiles: test     #测试环境
  application: 
    name: mircroservicecloud-config-client
eureka:
  instance:
    hostname: eureka7001.com
  client:
    register-with-eureka: false #自身不注册进eureka
    fetch-registry: false #不通过eureka获取注册信息
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/